# Generated by Django 2.1.4 on 2018-12-12 13:26

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20181211_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'None')], help_text='Valid Values: M or F', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 15 characters or fewer. Validated by ITU-T recommendation (E.164).', max_length=15, unique=True, validators=[
                users.validators.InternationNubmerValidator()], verbose_name='username'),
        ),
    ]
